// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ObjectStorage.DbContext;

namespace ObjectStorageWeb.Migrations
{
    [DbContext(typeof(ModelDbContext))]
    partial class ModelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("ObjectStorage.MetaModel.Class", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("model-classes");
                });

            modelBuilder.Entity("ObjectStorage.MetaModel.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClassName");

                    b.ToTable("model-properties");
                });

            modelBuilder.Entity("ObjectStorage.MetaModel.Property", b =>
                {
                    b.HasOne("ObjectStorage.MetaModel.Class", null)
                        .WithMany("Properties")
                        .HasForeignKey("ClassName");
                });
#pragma warning restore 612, 618
        }
    }
}
